from __future__ import annotations

from html.parser import HTMLParser


ARTIFACT_AUTHOR = "AI Learning Assistant @BA3073"


class _CreditPlacement(HTMLParser):
    def __init__(self, source: str):
        super().__init__()
        self.offsets = [0]
        for line in source.splitlines(keepends=True):
            self.offsets.append(self.offsets[-1] + len(line))
        self.body_start: int | None = None
        self.slide_start: int | None = None
        self.title_end: int | None = None
        self.credit_ranges: list[tuple[int, int]] = []
        self._credit_start: int | None = None
        self._credit_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        line, column = self.getpos()
        end = self.offsets[line - 1] + column + len(self.get_starttag_text())
        if tag == "div":
            if self._credit_start is not None:
                self._credit_depth += 1
            elif attributes.get("id") == "ai-learning-assistant-author":
                self._credit_start = end - len(self.get_starttag_text())
                self._credit_depth = 1
        if tag == "body" and self.body_start is None:
            self.body_start = end
        if tag == "section" and "slide" in (attributes.get("class") or "").split():
            if self.slide_start is None:
                self.slide_start = end

    def handle_endtag(self, tag: str) -> None:
        line, column = self.getpos()
        end = self.offsets[line - 1] + column + len(tag) + 3
        if tag == "h1" and self.title_end is None and self.body_start is not None:
            self.title_end = end
        if tag == "div" and self._credit_start is not None:
            self._credit_depth -= 1
            if self._credit_depth == 0:
                self.credit_ranges.append((self._credit_start, end))
                self._credit_start = None


def add_author_credit(source: str, *, slides: bool = False) -> str:
    """Add a deterministic visible byline before saving and rendering HTML."""
    placement = _CreditPlacement(source)
    placement.feed(source)
    # Revisions may already contain our old credit; replace and reposition it.
    for start, end in reversed(placement.credit_ranges):
        if start > 0 and source[start - 1] == "\n":
            start -= 1
        if source[end:end + 1] == "\n":
            end += 1
        source = source[:start] + source[end:]
    if placement.credit_ranges:
        placement = _CreditPlacement(source)
        placement.feed(source)

    style = (
        "display:block !important; visibility:visible !important; "
        "font:11px/1.4 Arial,sans-serif !important; color:#444 !important; "
    )
    if slides and placement.slide_start is not None:
        position = placement.slide_start
        # The credit stays inside the title slide, without creating another page.
        slide_css = '<style>section.slide { position:relative !important; }</style>'
        style += (
            "position:absolute !important; bottom:12px !important; "
            "left:24px !important; right:24px !important; z-index:1000; "
            "text-align:center; background:white;"
        )
    else:
        position = placement.title_end or placement.body_start or 0
        slide_css = ""
        style += "margin:0 0 12px; text-align:center; break-inside:avoid; column-span:all;"

    credit = (
        '<div id="ai-learning-assistant-author" style="' + style + '">'
        + slide_css + '© Generated by ' + ARTIFACT_AUTHOR + '</div>\n'
    )
    return source[:position] + "\n" + credit + source[position:]
