import pytest
from pypdf import PdfReader, PdfWriter

from backend.pipelines.authorship import ARTIFACT_AUTHOR, add_author_credit
from backend.pipelines.html_to_pdf import _set_pdf_author


@pytest.mark.parametrize("body", [
    '<body><h1>Essay</h1><p>Text</p></body>',
    '<BODY class="sheet"><main>Study notes</main></BODY>',
])
def test_credit_is_visible_inside_document_and_added_once(body):
    source = '<!doctype html><html><head></head>' + body + '</html>'
    credited = add_author_credit(source)
    assert '© Generated by ' + ARTIFACT_AUTHOR in credited
    assert credited.lower().index('<body') < credited.index('© Generated by ')
    assert credited.index('© Generated by ') < credited.lower().index('</body>')
    assert add_author_credit(credited) == credited


def test_slide_credit_stays_inside_first_slide():
    source = ("<!doctype html><html><body>"
              '<section class="slide title-slide"><div class="content"><h1>Title</h1></div></section>'
              '<section class="slide"><h2>Content</h2></section></body></html>')
    credited = add_author_credit(source, slides=True)
    assert credited.count('<section') == 2
    assert credited.index('<section') < credited.index('© Generated by ') < credited.index('</section>')
    assert credited.count('© Generated by ' + ARTIFACT_AUTHOR) == 1
    assert add_author_credit(credited, slides=True) == credited


def test_pdf_author_preserves_pages_and_other_metadata(tmp_path):
    path = tmp_path / "original.pdf"
    writer = PdfWriter()
    writer.add_blank_page(width=720, height=405)
    writer.add_blank_page(width=720, height=405)
    writer.add_metadata({"/Title": "A lecture", "/Author": "Old author"})
    writer.write(path)
    writer.close()

    _set_pdf_author(path)

    reader = PdfReader(path)
    assert reader.metadata.author == ARTIFACT_AUTHOR
    assert reader.metadata.title == "A lecture"
    assert len(reader.pages) == 2
    assert reader.pages[0].mediabox.width == 720
    assert reader.pages[0].mediabox.height == 405


@pytest.mark.parametrize("heading", [
    '<h1>Essay title</h1>',
    '<H1 class="title">Essay <em>title</em></H1>',
])
def test_essay_credit_is_between_title_and_abstract(heading):
    source = '<html><body><article>' + heading + '<section class="abstract"><h2>Abstract</h2><p>Summary</p></section></article></body></html>'
    credited = add_author_credit(source)
    assert credited.lower().index('</h1>') < credited.index('© Generated by ') < credited.index('<section class="abstract">')
    assert 'Author:' not in credited
    assert add_author_credit(credited) == credited


def test_revision_replaces_old_headline_credit():
    source = '<html><body>\n<div id="ai-learning-assistant-author">Author: AI Learning Assistant @BA3073</div>\n<article><h1>Title</h1><h2>Abstract</h2></article></body></html>'
    credited = add_author_credit(source)
    assert credited.count('© Generated by ' + ARTIFACT_AUTHOR) == 1
    assert 'Author:' not in credited
    assert credited.index('</h1>') < credited.index('© Generated by ') < credited.index('<h2>Abstract')
