#!/bin/zsh
# Stable launcher stub. Real logic lives in scripts/launcher-web.sh.
#
# DO NOT edit this file from Cursor or any other GUI app. macOS would
# then add com.apple.provenance and AppleSystemPolicy will SIGKILL the
# script on double-click before the launcher log is created. If a stub
# edit is unavoidable, run `bash scripts/bless-launchers.sh` from your
# own Terminal.app afterward.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)" || exit 1
cd "$SCRIPT_DIR" || exit 1
exec /bin/zsh ./scripts/launcher-web.sh "$@"
