from __future__ import annotations

from typing import Any

from backend.providers.base import TextGenerationRequest


class MockTextGenerationProvider:
    def generate_text(self, request: TextGenerationRequest) -> str:
        user_prompt = request.user_prompt.lower()
        system_prompt = request.system_prompt.lower()
        if "jupyter notebook" in user_prompt:
            return (
                '{"cells":[{"cell_type":"markdown","metadata":{},'
                '"source":["# Mocked solution\\n"]},{"cell_type":"code","metadata":{},'
                '"execution_count":null,"outputs":[],"source":["print(42)\\n"]}],'
                '"metadata":{},"nbformat":4,"nbformat_minor":5}'
            )
        if "slide decks as self-contained html" in system_prompt:
            return """<!doctype html>
<html><head><style>@page { size: 10in 5.625in; margin: 0; } .slide { width: 960px; height: 540px; page-break-after: always; } .content { padding: 54px; }</style></head>
<body><section class="slide title-slide"><div class="content"><p class="course-kicker">Mock Course</p><h1 class="lecture-title">Mocked Slide Deck</h1><p class="instructor">AI Learning Assistant</p></div></section><section class="slide"><div class="content"><h1>Key Idea</h1><p>This smoke-test deck proves the pipeline wrote source.</p></div></section></body></html>
"""
        if "cheat" in system_prompt:
            return """<!doctype html>
<html><head><style>@page { size: A4; margin: 8mm; } body { font-size: 10px; column-count: 3; column-gap: 10px; } section { break-inside: avoid; }</style></head>
<body><section><h1>Mocked Cheat Sheet</h1><p>Dense notes generated by the mocked provider for smoke testing.</p></section></body></html>
"""
        if "self-contained html" in system_prompt:
            return """<!doctype html>
<html><head><style>@page { size: A4; margin: 20mm; } body { font-family: serif; }</style></head>
<body><h1>Mocked Essay</h1><p>This smoke-test essay proves the pipeline wrote source.</p></body></html>
"""
        return (
            "def solve():\n"
            "    return 'mocked pipeline output'\n\n"
            "if __name__ == '__main__':\n"
            "    print(solve())\n"
        )


def test_mock_provider(profile: dict[str, Any], _api_key: str) -> dict[str, Any]:
    return {"ok": True, "provider": profile["provider"], "model": profile["model"]}
